server:
  port: 8081
  context-path: /crm

spring:
  data:
    mongodb:
      authentication-database: false
      database: local
      host: 172.31.81.228
      port: 27018
  redis:
    database: 15
    host: 172.31.81.228
    password: 888888
    pool:
      max-active: 200
      max-idle: 10
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 1000
  datasource:
    name: test
    url: jdbc:mysql://172.31.81.228:3307/newretail?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 888888
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: package com.hema.newretail.backstage.entry # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: Count=countSql
logging:
  level:
    com.hema.newretail.backstage.dao: debug
weixin:
  appId: wx5cca670556d1acdd
  appSecret: 646acc89222268d55cb259812d62594a
  templateId: s554M8pMLweVToIJNJv8SSXdFUhD28zrlryI0mpxRlg
excelModel:
  srcFileName: 用户数据导出20180824194505.xlsx
  orderSrcFileName: 订单数据导出.xlsx
  agentFileName: 代理公司导出.xlsx

custom:
  initUserPassWord: 123456
  #debug: true
  #auth
auth:
  requestCodeUrl: http://118.190.159.229:8082/auth/authentication/codeAuth
  requestAccessCodeUrl: http://118.190.159.229:8082/auth/authorization/token

oss:
  endpoint : oss-cn-qingdao.aliyuncs.com
  access_key_id : LTAIsmLY9xXmN5B1
  access_key_secret : wTfmgSyXFhZCHQD7vdQTKgs3mXTrwj
  backet_name : shandong-hema-oss
  folder_json : json/
  folder_img : img/
  web_url: http://newretail.hemaapp.com/
